- hosts: all
  vars:
    dotfile_branch: "master"
    decrypt_bri: false
    decrypt_elip: false
    decrypt_cjl: false
    ripgrep_version: 15.1.0
    fd_version: 10.3.0
    use_zsh: true

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: no
      force_apt_get: true
      update_cache: true
      cache_valid_time: 86400 #One day
      state: present
    when: ansible_os_family == "Debian"

  - name: Update Package Manager
    become: true
    pacman:
      update_cache: true
      state: present
    when: ansible_os_family == "Archlinux"

  - name: Setup my environment
    hosts: localhost
    become: yes
    tasks:  # <--- tasks is a peer to hosts
  - name: Remove conflicting fd-find
    ansible.builtin.apt:
      name: fd-find
      state: absent

  - name: Install other tools
    ansible.builtin.apt:
      name: nvim
      state: present

  tasks:
    - include_tasks: setup-Debian.yml
      when: ansible_os_family == 'Debian'
      tags: [setup, core, ssh, base16, nvim, tmux, zsh, dotfiles, private_aliases]

    - include_tasks: setup-additional-Debian.yml
      when: ansible_os_family == 'Debian' and ansible_architecture == "x86_64"
      tags: [brave, nix, ghostty, additional]

    - include_tasks: setup-Archlinux.yml
      when: ansible_os_family == "Archlinux"
      tags: [setup, core, ssh, base16, nvim, tmux, zsh, dotfiles, hyprland, private_aliases]

    - include_tasks: setup-additional-Archlinux.yml
      when: ansible_os_family == "Archlinux"
      tags: [brave, nix, ghostty, spotify, additional, yay]
